### ISSUE TITLE
Can't get iIP and port from client.

### ISSUE THREAD

**Issue by Malkverbena** [LudiDorici/gd-custom-multiplayer#1]
Hi,
When using WS,  multiplayer.network_peer.get_peer_address(id) returns only "" and multiplayer.network_peer.get_peer_port(id) returns only 0.
Not sure if it's a engine issue or project issue. I had no time to investigate yet.

SO: Ubuntu.

**Comment by Faless** [comment]
Can you explain a bit better? Do you get any error in the debugger? Are you
trying to get the IP of a client from another client? Or from the server?

This seems a problem in Godot in case, as we do not override network_peer

**Comment by Malkverbena** [comment]
Not in debugger. Actually, there is no error.
The functions returns values. get_peer_address returns a string, always ""  and get_peer_port returnt an int, which is always 0.
On this lines for exemple:

>63 		_log("%s:%s connected!" % [
64			multiplayer.network_peer.get_peer_address(id),
65			multiplayer.network_peer.get_peer_port(id)
66		])

You get this result.

**Comment by Faless** [comment]
So are you using the code without any sort of modification?

**Comment by Malkverbena** [comment]
Yes. But works fine with enet.

**Comment by Faless** [comment]
Okay, it's a bug in Godot source, will fix it ASAP

**Comment by Malkverbena** [comment]
![captura de tela de 2018-06-06 11-18-19](https://user-images.githubusercontent.com/26177016/41043942-716d2b2c-697b-11e8-9a49-2e3c10e3791b.png)


Thank you!

**Comment by Faless** [comment]
Fixed via godotengine/godot#19397
